language: php

before_script:
 - composer install

php:
  - 5.4
  - 5.5
  - 5.6

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml --configuration phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
